name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev gcovr
    - name: Checkout Repository and Submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build --target Tests
    - name: Run Tests
      run: build/Tests
    - name: Create Coverage Report
      run: gcovr --xml --output coverage.xml --root src build
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
        verbose: true