name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install libcurl
      run: sudo apt-get install -y libcurl4-openssl-dev
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run CMake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
